### ISSUE TITLE
Test failing due to the mutliple definition of keywords

### ISSUE THREAD

**Issue by llipavsky** [ncbi/robotframework-pageobjects#47] opened 2015-06-12 13:59 UTC
Hi, after updating to 1.3.0, all tests fail with following:

12-Jun-2015 14:08:30	[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: Multiple keywords with name 'Capture Page Screenshot' found.
12-Jun-2015 14:08:30	Give the full name of the keyword you want to use.
12-Jun-2015 14:08:30	Found: 'LoginPage.SafeqLoginPage.Capture Page Screenshot' and 'Selenium2Library.Capture Page Screenshot'
12-Jun-2015 14:08:34	[ WARN ] Keyword 'Capture Page Screenshot' could not be run on failure: Multiple keywords with name 'Capture Page Screenshot' found.
12-Jun-2015 14:08:34	Give the full name of the keyword you want to use.
12-Jun-2015 14:08:34	Found: 'LoginPage.SafeqLoginPage.Capture Page Screenshot' and 'Selenium2Library.Capture Page Screenshot'

Is it possible to somehow handle this on Page level? Or do we have now to rewrite our tests to specify which one we want?

in 1.2.1, there were no issues like this. Thanks

**Comment by frishberg** [comment] 2015-06-12 14:00
Yes, I am seeing this bug as well and working on a fix. Please use version 1.2.1 for now. Thank you for reporting this.

**Comment by llipavsky** [comment] 2015-06-12 14:01
Thanks

**Comment by frishberg** [comment] 2015-06-12 18:15
Hi there. The bug is fixed now. Would you mind reinstalling version 1.3.0 (I removed the old one, and the new one will be in PyPI soon) and running your tests again?

**Comment by kahunacohen** [comment] 2015-06-12 18:58
@frishberg maybe a note on the googlegroups robot user group would be good. Since it seems a bunch of people are using this package now. That's good news.

**Comment by frishberg** [comment] 2015-06-12 21:05
Good point, @kahunacohen. Once @llipavsky has confirmed that it works for him, I'll make a note on the user group.

**Comment by ezamin7** [comment] 2015-06-15 09:39
Hello everyone. Thanks for looking into this issue, we are seeing the same problem here.

@frishberg: something seems to be wrong with the package at PyPI. When I run `pip install -U robotframework-pageobjects`, version 1.2.1 is being installed.

The page at PyPI doesn't list the .tar.gz file  for 1.3.0; it looks like it's not there:
https://pypi.python.org/pypi/robotframework-pageobjects/1.3.0

(have a look at https://pypi.python.org/pypi/robotframework-pageobjects/1.2.1 for comparison)

**Comment by llipavsky** [comment] 2015-06-15 10:58
same for me - so cannot verify

**Comment by hellmanj** [comment] 2015-06-15 14:36
Sorry for the hiccup, not sure what went wrong there.  We released 1.3.1 (with no changes from 1.3.0) just to make sure we got a good package on PyPI.

**Comment by ezamin7** [comment] 2015-06-15 16:47
Thanks, it can be installed now. I'm running some tests, will post feedback here once I'm done.

**Comment by ezamin7** [comment] 2015-06-15 18:18
Hi,

My tests are failing with the following error:

`No keyword with name 'Go To <Page-Name>' found.`

I've added a script to reproduce the error here: https://gist.github.com/ezamin7/050bed70ed3a601f5e3a/download

**Comment by frishberg** [comment] 2015-06-15 18:47
OK, I am looking into it now.

**Comment by frishberg** [comment] 2015-06-15 21:54
Everyone, I rolled back to 1.2.1 again. I am working on a fix, but it will require some refactoring and thought, and given other priorities, it may be a few weeks before this feature is released. Meanwhile, please just use 1.2.1. Thank you all for your help debugging.

**Comment by kahunacohen** [comment] 2015-07-01 12:38
I think we can close this. The main issue is the implementation of the feature which caused side effects, and thus we rolled back (for now). @frishberg what's the status of being able to use selectors from Robot tests? Did we release that yet?

**Closed by kahunacohen** 2015-07-01 12:38 UTC

**Comment by frishberg** [comment] 2015-07-01 14:19
No, we haven't released it yet. Depending on priorities, maybe in the next couple of weeks?

**Comment by ZiedWD** [comment] 2015-09-01 08:30
Hello, Any news about the fix for this issue, I am facing this problem now and when downgrading page object lib other tests stop working.
Thanks
